/* TIP: use https://www.npmjs.com/package/keymirror lib in order to
simplify creation of same-named key-value pairs */
const ADD_NEW_FORM_CHANGED = "ADD_NEW_FORM_CHANGED";
const ADD_NEW_FORM = "ADD_NEW_FORM";
const ADD_NEW_FIELD = "ADD_NEW_FIELD";
const ADD_TEXT_INPUT_FIELD = "ADD_TEXT_INPUT_FIELD";
const ADD_TEXTAREA_INPUT_FIELD = "ADD_TEXTAREA_INPUT_FIELD";
const EDIT_INPUT_TEXT_FIELD = "EDIT_INPUT_TEXT_FIELD";
const EDIT_INPUT_TEXTAREA_FIELD = "EDIT_INPUT_TEXTAREA_FIELD";
const DELETE_FORM = "DELETE_FORM";
const DELETE_FIELD = "DELETE_FIELD";
const CLEAR_CURRENT_FORM = "CLEAR_CURRENT_FORM";
const SET_LINKED_FORM = "SET_LINKED_FORM";

export {
  ADD_NEW_FORM_CHANGED,
  ADD_NEW_FORM,
  ADD_NEW_FIELD,
  ADD_TEXT_INPUT_FIELD,
  ADD_TEXTAREA_INPUT_FIELD,
  EDIT_INPUT_TEXT_FIELD,
  EDIT_INPUT_TEXTAREA_FIELD,
  DELETE_FORM,
  DELETE_FIELD,
  CLEAR_CURRENT_FORM,
  SET_LINKED_FORM
};
